### ISSUE TITLE
Tutor bro

### ISSUE THREAD

**Issue by Aldizen21** [ndowerdev/nodejs-agc#1]
Bagi contact

**Comment by ndowerdev** [comment]
discord `yourrain#7662`

**Comment by ndowerdev** [comment]
dah ane update sample config sama rules bro

**Comment by Aldizen21** [comment]
Cek DC bro

**Comment by Aldizen21** [comment]
Klo versi cpanel gmn bro?

**Comment by ndowerdev** [comment]
cpanel g tau, soalnya ga ada make lagi sejak 2016
